name: Android CI

on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gradle
      run: |
        sudo apt-get update
        sudo apt-get install gradle
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd app
        ../gradlew build
